# Generated by Django 3.2.9 on 2021-12-03 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DoctorClinic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to='Doctor.clinic'),
        ),
    ]
