# Generated by Django 3.2.9 on 2021-12-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_alter_doctor_doctorclinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DoctorClinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to='Doctor.clinic'),
        ),
    ]
