# Generated by Django 3.2.9 on 2021-12-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_alter_doctor_doctorclinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='DoctorImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
