# Generated by Django 3.2.9 on 2021-12-04 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='AppointmentSlot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='Appointment.slot'),
        ),
    ]
