# Generated by Django 3.2.9 on 2021-12-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_patient_patientpassword'),
        ('Doctor', '0004_doctor_doctorimage'),
        ('Appointment', '0002_alter_appointment_appointmentslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='AppointmentClinic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointmentclinic', to='Doctor.clinic'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='AppointmentDoctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointmentdoctor', to='Doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='AppointmentPatient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointmentpatient', to='Patient.patient'),
        ),
    ]
