# Generated by Django 3.2.9 on 2021-12-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_remove_patient_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='PatientPassword',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
